CREATE DATABASE IF NOT EXISTS agendaversa;

USE agendaversa;

CREATE TABLE usuario (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nome VARCHAR(45) NOT NULL,
    sobrenome VARCHAR(100) NOT NULL,
    email VARCHAR(140) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tarefa (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    titulo VARCHAR(45) NOT NULL,
    descricao VARCHAR(100),
    hora_inicio DATETIME not null,
    hora_fim DATETIME not null,
    usuario_id INT not null,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE INDEX idx_usuario_id ON tarefa(usuario_id);
